import { z } from 'zod';

/**
 * Published external-contract vocabularies, mirrored from LettrLabs.App's
 * `[SchemaEnum]`-annotated external `/v1/*` contract.
 *
 * Source of truth: the served external OpenAPI at `/api/openapi/v3.json`
 * (generated by the App's `SchemaEnumFilter` from the C# enums cited below).
 * These constants are consumed by the curated tool descriptions/validators and
 * reconciled against `test/fixtures/openapi.external.json` by
 * `test/openapi/contract-drift.test.ts` — so a drift between this file and the
 * published contract fails a test rather than silently rotting the bridge.
 *
 * Keep in sync when the App external contract changes.
 */

// Order status — LettrLabsOrderStatus (Description spelling), published on
// ExternalOrdersGetOrdersDetailResponseVm.Status. Response vocabulary
// (LettrLabs.App: source/_Core/LettrLabs.App.Contracts/Enums/OrderStatus.cs).
export const ORDER_STATUSES = [
  'Draft',
  'Edits Needed',
  'Payment Needed',
  'Paid',
  'Ready For Production',
  'In Production',
  'In QA',
  'InShipping',
  'Mailed',
  'Refunded',
  'Cancelled',
  'Deleted',
  'Error',
] as const;

// Recipient delivery status — RecipientDeliveryStatuses, published on
// ExternalOrdersRecipientDeliveryStatusVm.Status (GET /v1/order/{id}/recipient-delivery-status)
// (LettrLabs.App: source/_Core/LettrLabs.App.Contracts/Enums/OrderTransactionVocabulary.cs).
export const DELIVERY_STATUSES = [
  'Waiting on USPS Info',
  'Mailed',
  'In Transit',
  'At Local Facility',
  'Undeliverable',
  'Delivered',
  'No Tracking Available',
] as const;

// Postage — checkout INPUT vocabulary. Published as
// `[SchemaEnum(PostageTypes.Standard, PostageTypes.FirstClass)]` on
// ExternalOrdersPostCheckoutVm.PostageType — deliberately NARROWER than the
// response PostageTypes set (which also carries HailTrace for storm mail, not
// externally chargeable). The input enum is therefore already current; do not
// widen it to the response set.
export const PostageType = z.enum(['Standard', 'FirstClass']);
export const POSTAGE_TYPES = PostageType.options;

// Production speed — checkout INPUT vocabulary. Published as
// `[SchemaEnum(Normal, ExpeditedFaster, ExpeditedFastest)]` on
// ExternalOrdersPostCheckoutVm.ProductionSpeed — narrower than the response
// ProductionSpeed enum (which also carries HailTrace).
export const ProductionSpeed = z.enum(['Normal', 'ExpeditedFaster', 'ExpeditedFastest']);
export const PRODUCTION_SPEEDS = ProductionSpeed.options;
